### ISSUE TITLE
Two questions about the original paper

### ISSUE THREAD

**Issue by xyliugo** [microsoft/simulated-trial-and-error#11]
Thank you for your interesting work! After reading your paper, I have a few small questions I would like to confirm with you:
1. Is the main purpose of STE to provide a set of high-quality tool use examples, and then augment LLMs with tools, under both in-context learning and fine-tuning settings?
2. In Table 1, are the baselines directly calling the corresponding LLMs? I mean, we all know that ICL could improve the tool invocation accuracy of LLMs, but it seems I didn't see baselines based on ICL.

All in all, I think STE is a GOOD paper. Looking forward to your further explanation :D.

**Comment by Boshi-Wang** [comment]
Thanks for your interest in our work!

1. The main purpose of STE is to gather an informative set of tool-use experiences (in the form of a sequence of trial and error trajectories) in similar ways as how humans learn to master tools. The experiences could then be utilized to enhance LLMs' tool use abilities. Currently we are adopting a straightforward way by extracting positive tool-use examples from the experiences for ICL/FT, and there could also be other ways such as incorporating errors/negative examples, similar in spirit to some recent work such as https://arxiv.org/pdf/2402.05403.pdf.

2. The baselines call the LLMs with instructions and tool descriptions in the prompt, as there are no accompanying tool-use examples for doing ICL (certain tools may have a few examples in the descriptions though). After STE, the distilled set of tool-use examples could then serve as demonstration examples for ICL.

Hope this answers your questions!
