### ISSUE TITLE
whatt's the difference among training data sets, tool_data_train_STE_full.json, tool_data_train_STE_no_reflection.json. in fact, i can't get the difference among the files you provide 

### ISSUE THREAD

**Issue by NorkeyChen** [microsoft/simulated-trial-and-error#12]

**Comment by Boshi-Wang** [comment]
These are different tool-use training data obtained from various exploration settings in our ablation study, where "full" means the full STE method and the remaining ones ablate different components of STE. More details are included in Section 4.2 and Table 2; feel free to check them out!
